version: "3"

services:
  tests:
    image: "python:3.6-alpine"
    volumes:
      - .:/src
      - pip-cache:/root/.cache/pip
    working_dir: /src
    command: sh -c "while ! nc neo4j 7687; do  sleep 1; done; python -B setup.py test"
    links:
      - neo4j
    environment:
      NEO4J_BOLT_URL: bolt://neo4j:neo4j@neo4j:7687
  neo4j:
    image: "neo4j:3.1"
    environment:
      NEO4J_AUTH: none

volumes:
  pip-cache:
    driver: local
